spring:
  application:
    name: gym_system
  server.port: 8080
  datasource:
        url: jdbc:postgresql://localhost:5432/gym_system_db
        username: mohamed
        password: mohamed
        driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: mySuperSecretKeyForJwtAuthentication123456789
    expiration: 86400000
logging:
  level:
    com:
      gym: DEBUG



